"""Domain models for internal use."""
from dataclasses import dataclass
from datetime import datetime
from typing import Dict


@dataclass
class AnalysisResult:
    """Internal representation of analysis results."""
    summary: str
    files: Dict[str, str]
    timestamp: datetime = None
    
    def __post_init__(self):
        """Set timestamp if not provided."""
        if self.timestamp is None:
            self.timestamp = datetime.utcnow()
    
    def to_response(self) -> dict:
        """Convert to API response format."""
        # Return ALL generated files, not just a subset
        # This ensures we don't lose any files generated by the AI
        return {
            "analysis_summary": self.summary,
            "generated_files": self.files  # Return all files as-is
        }
